apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: mr-teddycloud
  name: mr-teddycloud-pvc-data
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      usage: mr-teddycloud-pv-data