apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: mr-teddycloud
  name: mr-teddycloud-pv-data
  labels:
    usage: mr-teddycloud-pv-data
spec:
  capacity:
    storage: 32Gi
  storageClassName: tc-nfs
  accessModes:
  - ReadWriteMany
#  persistentVolumeReclaimPolicy: Recycle
  volumeMode: Filesystem
#  mountOptions:
#   - hard
#   - nfsvers=4.1
  nfs:
    server: mr0.local
    path: "/srv/nfs4/homes/mr/teddycloud"
    readOnly: false
